server:
  port: 10004
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/
spring:
  application:
    name: service-feign

# feign自带断路器 开启
feign:
  hystrix:
    enabled: true