#spring.application.name 这里的name对应了配置文件中的application部分
#spring.cloud.config.label 指明远程仓库的分支
#spring.cloud.config.profile
#  dev开发环境配置文件
#  test测试环境
#  pro正式环境
#spring.cloud.config.uri= http://localhost:8888/ 指明配置服务中心的网址。

server:
  port: 10009
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

data:
  env: NaN
  user:
    username: NaN
    password: NaN